### ISSUE TITLE
Add relevant php files to repository?

### ISSUE THREAD

**Issue by sethlatte** [basilthebeagles/pythonCryptolockerExample#1]
It would be appreciated if you could add bitcoinManager.php (the blockchain callback function) and checker.php to the repository.

**Comment by basilthebeagles** [comment]
The removal of theses files from the repository is intentional. Their removal acts as an extra barrier of entry to malicious use of this.
Instead though I could give further information on how they work?

**Comment by sethlatte** [comment]
That would be much appreciated!

**Comment by basilthebeagles** [comment]
Read up on this here :https://blockchain.info/api/api_receive

Anyway bitcoinManager.php is called by the blockchain api whenever ANY amount of bitcoins is sent to the temp address.
bitcoinManager will check how many BTC has been received, if it is more or equal to the value needed then it will log the address in a mySQL database.

bitcoinChecker checks the database to see if the address is in it, if it is it will return a something saying it has and the program will then unlock the files.

May I ask why you are asking about this?
